tap "achannarasappa/tap", "https://github.com/achannarasappa/tap.git"
tap "browsh-org/browsh"
tap "jotta/cli"
tap "lizardbyte/homebrew"
tap "macos-fuse-t/cask"
tap "nikitabobko/tap"
tap "samtay/tui"
tap "valkyrie00/bbrew"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Improved top (interactive process viewer)
brew "htop"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Rsync for cloud storage
brew "rclone"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
cargo "atuin"
cargo "bat"
cargo "cargo-binstall"
cargo "dysk"
cargo "eza"
cargo "fd-find"
cargo "ripgrep"
cargo "starship"
cargo "tealdeer"
cargo "television"
cargo "yazi-cli"
cargo "yazi-fm"
cargo "zoxide"
flatpak "be.alexandervanhee.gradia"
flatpak "com.bitwarden.desktop"
flatpak "com.github.marhkb.Pods"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.google.Chrome"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.ranfdev.DistroShelf"
flatpak "dev.deedles.Trayscale"
flatpak "io.github.fabrialberio.pinapp"
flatpak "io.github.flattool.Ignition"
flatpak "io.github.flattool.Warehouse"
flatpak "io.github.kolunmi.Bazaar"
flatpak "io.gitlab.adhami3310.Impression"
flatpak "io.missioncenter.MissionCenter"
flatpak "it.mijorus.gearlever"
flatpak "net.codelogistics.webapps"
flatpak "org.gnome.Calculator"
flatpak "org.gnome.Characters"
flatpak "org.gnome.Connections"
flatpak "org.gnome.Contacts"
flatpak "org.gnome.Decibels"
flatpak "org.gnome.DejaDup"
flatpak "org.gnome.FileRoller"
flatpak "org.gnome.Firmware"
flatpak "org.gnome.Logs"
flatpak "org.gnome.Loupe"
flatpak "org.gnome.Maps"
flatpak "org.gnome.NautilusPreviewer"
flatpak "org.gnome.Papers"
flatpak "org.gnome.SimpleScan"
flatpak "org.gnome.Snapshot"
flatpak "org.gnome.SoundRecorder"
flatpak "org.gnome.TextEditor"
flatpak "org.gnome.Weather"
flatpak "org.gnome.baobab"
flatpak "org.gnome.clocks"
flatpak "org.gnome.font-viewer"
flatpak "org.mozilla.firefox"
flatpak "page.tesk.Refine"
