tap "projectbluefin/bluefinctl", trusted: true
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Enable transparent encryption/decryption of files in a git repo
brew "git-crypt"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Rsync for cloud storage
brew "rclone"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
cargo "atuin"
cargo "bat"
cargo "cargo-binstall"
cargo "dysk"
cargo "eza"
cargo "fd-find"
cargo "ripgrep"
cargo "starship"
cargo "tealdeer"
cargo "television"
cargo "yazi-cli"
cargo "yazi-fm"
cargo "zoxide"
flatpak "app.devsuite.Ptyxis"
flatpak "be.alexandervanhee.gradia"
flatpak "com.bitwarden.desktop"
flatpak "com.github.PintaProject.Pinta"
flatpak "com.github.marhkb.Pods"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.google.Chrome"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.ranfdev.DistroShelf"
flatpak "io.github.fabrialberio.pinapp"
flatpak "io.github.flattool.Ignition"
flatpak "io.github.flattool.Warehouse"
flatpak "io.github.kolunmi.Bazaar"
flatpak "io.gitlab.adhami3310.Impression"
flatpak "io.missioncenter.MissionCenter"
flatpak "it.mijorus.gearlever"
flatpak "it.mijorus.smile"
flatpak "org.gnome.Calculator"
flatpak "org.gnome.Calendar"
flatpak "org.gnome.Characters"
flatpak "org.gnome.Connections"
flatpak "org.gnome.Contacts"
flatpak "org.gnome.Decibels"
flatpak "org.gnome.DejaDup"
flatpak "org.gnome.FileRoller"
flatpak "org.gnome.Firmware"
flatpak "org.gnome.Logs"
flatpak "org.gnome.Loupe"
flatpak "org.gnome.Maps"
flatpak "org.gnome.NautilusPreviewer"
flatpak "org.gnome.Papers"
flatpak "org.gnome.Showtime"
flatpak "org.gnome.SimpleScan"
flatpak "org.gnome.Snapshot"
flatpak "org.gnome.SoundRecorder"
flatpak "org.gnome.TextEditor"
flatpak "org.gnome.Weather"
flatpak "org.gnome.baobab"
flatpak "org.gnome.clocks"
flatpak "org.gnome.font-viewer"
flatpak "org.mozilla.firefox"
flatpak "org.mozilla.thunderbird_esr"
flatpak "page.tesk.Refine"
