tap "achannarasappa/tap"
tap "browsh-org/browsh"
tap "jotta/cli"
tap "lizardbyte/homebrew"
tap "macos-fuse-t/cask"
tap "nikitabobko/tap"
tap "samtay/tui"
tap "valkyrie00/bbrew"
# Aquarium animation in ASCII art
brew "asciiquarium"
# Preexec and precmd functions for Bash (like Zsh)
brew "bash-preexec"
# GNU compiler collection
brew "gcc"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Tool to install, manage and use Progressive Web Apps in Mozilla Firefox
brew "firefoxpwa"
# Improved top (interactive process viewer)
brew "htop"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Modern and intuitive terminal-based text editor
brew "micro"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Podman Terminal User Interface
brew "podman-tui"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Cross-platform library for audio I/O
brew "portaudio"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Display and control your Android device
brew "scrcpy"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Organize software neatly under a single directory tree (e.g. /usr/local)
brew "stow"
# Performance monitoring tools for Linux
brew "sysstat"
# Command-line interface to the freedesktop.org trashcan
brew "trash-cli"
# Ultra fast grep with query UI, fuzzy search, archive search, and more
brew "ugrep"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Android SDK component
cask "android-platform-tools"
cargo "atuin"
cargo "bat"
cargo "cargo-binstall"
cargo "dysk"
cargo "eza"
cargo "fd-find"
cargo "linutil_tui"
cargo "ripgrep"
cargo "starship"
cargo "tealdeer"
cargo "television"
cargo "yazi-build"
cargo "yazi-cli"
cargo "yazi-fm"
cargo "zoxide"
flatpak "com.bitwarden.desktop"
flatpak "com.brave.Browser"
flatpak "com.discordapp.Discord"
flatpak "com.github.PintaProject.Pinta"
flatpak "com.github.jeromerobert.pdfarranger"
flatpak "com.github.marhkb.Pods"
flatpak "com.github.tchx84.Flatseal"
flatpak "com.google.Chrome"
flatpak "com.mattjakeman.ExtensionManager"
flatpak "com.obsproject.Studio"
flatpak "com.ranfdev.DistroShelf"
flatpak "dev.deedles.Trayscale"
flatpak "dev.fredol.open-tv"
flatpak "io.github.diegopvlk.Cine"
flatpak "io.github.fabrialberio.pinapp"
flatpak "io.github.flattool.Ignition"
flatpak "io.github.flattool.Warehouse"
flatpak "io.github.kolunmi.Bazaar"
flatpak "io.gitlab.adhami3310.Impression"
flatpak "io.missioncenter.MissionCenter"
flatpak "io.sourceforge.pysolfc.PySolFC"
flatpak "it.mijorus.gearlever"
flatpak "it.mijorus.smile"
flatpak "net.codelogistics.webapps"
flatpak "net.nokyan.Resources"
flatpak "net.retrodeck.retrodeck"
flatpak "org.cockpit_project.CockpitClient"
flatpak "org.freefilesync.FreeFileSync"
flatpak "org.gnome.Calculator"
flatpak "org.gnome.Calendar"
flatpak "org.gnome.Characters"
flatpak "org.gnome.Connections"
flatpak "org.gnome.Contacts"
flatpak "org.gnome.DejaDup"
flatpak "org.gnome.FileRoller"
flatpak "org.gnome.Firmware"
flatpak "org.gnome.Geary"
flatpak "org.gnome.Logs"
flatpak "org.gnome.Loupe"
flatpak "org.gnome.Mahjongg"
flatpak "org.gnome.Maps"
flatpak "org.gnome.NautilusPreviewer"
flatpak "org.gnome.NetworkDisplays"
flatpak "org.gnome.Papers"
flatpak "org.gnome.Showtime"
flatpak "org.gnome.SimpleScan"
flatpak "org.gnome.Snapshot"
flatpak "org.gnome.SoundRecorder"
flatpak "org.gnome.TextEditor"
flatpak "org.gnome.Weather"
flatpak "org.gnome.baobab"
flatpak "org.gnome.clocks"
flatpak "org.gnome.font-viewer"
flatpak "org.gnome.gitlab.wwarner.Solitaire"
flatpak "org.gnome.meld"
flatpak "org.gnome.seahorse.Application"
flatpak "org.jellyfin.JellyfinDesktop"
flatpak "org.mozilla.firefox"
flatpak "org.pulseaudio.pavucontrol"
flatpak "page.tesk.Refine"
flatpak "tv.kodi.Kodi"
npm "@google/gemini-cli"
npm "pnpm"
