- Infrastructure:
    - Cockpit:
        icon: cockpit-light
        href: https://cockpit.hemati.com
        description: Bazzite Dashboard 
        ping: http://192.168.1.18:9090
    - Cloudflare:
        icon: cloudflare
        href: https://t.ly/6gAzk
        description: Reverse-Proxy 
        server: podman
        container: cloudflared
    - Sunshine:
        icon: sunshine
        href: https://100.120.205.70:47990
        description: Game Streaming 
        ping: http://localhost:47990 

- Servers:
    - Nextcloud:
        icon: nextcloud
        href: https://cloud.hemati.com
        description: Private File Storage
        server: podman
        container: nextcloud
    - Immich:
        icon: immich
        href: https://photos.hemati.com
        description: Photo & Video Backup
        server: podman
        container: immich-server
    - Samba:
        icon: samba-server
        href: https://app.plex.tv
        description: Media SMB Share 
        server: podman
        container: samba

- Streaming:
    - Stremio:
        icon: stremio
        href: https://web.stremio.com
        description: Freedom to Stream 
        server: podman
        container: stremio-server 
    - AIOStreams:
        icon: https://t.ly/mVFPd
        href: https://aiostreams.hemati.com
        description: Stream Aggregator
        server: podman
        container: aiostreams
    - MediaFlow:
        icon: https://mediaflowtools.com/mediaflow-logo.svg
        href: https://mediaflow.hemati.com
        description: Debrid Cache Proxy
        server: podman
        container: mediaflow
    - Jellyfin:
        icon: jellyfin
        href: https://media.hemati.com
        description: Home Media Server
        server: podman
        container: jellyfin
    - Zurg:
        icon: real-debrid
        href: https://real-debrid.com
        description: Organize Media 
        server: podman
        container: zurg

