---
- System:
    - Cloudflare:
        icon: cloudflare
        href: https://dash.cloudflare.com/67304fcb508ed8114c9625fb9a98aff1/home/overview
        description: Reverse-Proxy 
        server: podman
        container: cloudflared
    - Cockpit:
        icon: cockpit-light
        href: https://cockpit.hemati.com
        description: Bazzite Dashboard 
        ping: http://192.168.1.18:9090
    - Samba:
        icon: samba-server
        href: https://app.plex.tv
        description: Media SMB Share 
        server: podman
        container: samba

- Servers:
    - AIOStreams:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/aiostreams-light.svg
        href: https://aiostreams.hemati.com
        description: Stream Aggregator
        server: podman
        container: aiostreams
    - Immich:
        icon: immich
        href: https://photos.hemati.com
        description: Photo & Video Backup
        ping: http://immich-server:2283
    - Jellyfin:
        icon: jellyfin
        href: https://media.hemati.com
        description: Home Media Server
        ping: http://jellyfin:8096
    - Nextcloud:
        icon: nextcloud
        href: https://cloud.hemati.com
        description: Private File Storage
        ping: http://nextcloud:80
    - Stremio:
        icon: stremio
        href: https://web.stremio.com
        description: Freedom to Stream 
        server: podman
        container: stremio-server 
    - StremThru:
        icon: https://pb.dashboardicons.com/api/files/community_gallery/ix4re5u6udy2may/256_3xh027hgmz.png
        href: https://stremthru.hemati.com
        description: Debrid Cache Proxy
        server: podman
        container: stremthru
    - Sunshine:
        icon: sunshine
        href: https://100.120.205.70:47990
        description: Game Streaming 
        ping: http://localhost:47990 
    - Zurg:
        icon: real-debrid
        href: https://real-debrid.com
        description: Organize Media 
        server: podman
        container: zurg

