title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: false

layout:
  Infrastructure:
    style: row
    columns: 3
  Management:
    style: column
    columns: 1
    header: false
  Servers:
    style: row
    columns: 4
  Streaming:
    style: row
    columns: 5
  Sites:
    style: row
    columns: 4
