title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: true

layout:
  Servers:
    style: row
    columns: 3
  Streaming:
    style: row
    columns: 4
  Sites:
    style: row
    columns: 4
