title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: true

layout:
  Media:
    style: row
    columns: 4 
  Cloud:
    style: row
    columns: 4 
  Utilities:
    style: row
    columns: 4
  Infrastructure:
    style: row
    columns: 5
  Security:
    style: row
    columns: 1
