format = """
[](#3B4252)\
$python\
$username\
[](fg:#3B4252 bg:#434C5E)\
$container\
[](fg:#434C5E bg:#4C566A)\
$directory\
[](fg:#4C566A bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#06969A bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[ $user ]($style)'

# Custom container module
[container]
symbol = ""
format = '[ $symbol ]($style)'
style = 'bg:#434C5E'
disabled = false

[directory]
style = "bg:#4C566A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " 󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
".config" = "  "
".local" = " ⌘ "
"debrid-stack" = "  "

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#86BBD8"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#06969A"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[os.symbols]
AIX = "➿ "
Alpaquita = "🔔 "
AlmaLinux = "💠 "
Alpine = "🏔️ "
Amazon = "🙂 "
Android = "🤖 "
Arch = "🎗️ "
Artix = "🎗️ "
Bluefin = "🐟 "
CachyOS = "🎗️ "
CentOS = "💠 "
Debian = "🌀 "
DragonFly = "🐉 "
Emscripten = "🔗 "
EndeavourOS = "🚀 "
Fedora = "🎩 "
FreeBSD = "😈 "
Garuda = "🦅 "
Gentoo = "🗜️ "
HardenedBSD = "🛡️ "
Illumos = "🐦 "
Kali = "🐉 "
Linux = "🐧 "
Mabox = "📦 "
Macos = "🍎 "
Manjaro = "🥭 "
Mariner = "🌊 "
MidnightBSD = "🌘 "
Mint = "🌿 "
NetBSD = "🚩 "
NixOS = "❄️ "
Nobara = "🎩 "
OpenBSD = "🐡 "
OpenCloudOS = "☁️ "
openEuler = "🦉 "
openSUSE = "🦎 "
OracleLinux = "🦴 "
Pop = "🍭 "
Raspbian = "🍓 "
Redhat = "🎩 "
RedHatEnterprise = "🎩 "
RockyLinux = "💠 "
Redox = "🧪 "
Solus = "⛵ "
SUSE = "🦎 "
Ubuntu = "🎯 "
Ultramarine = "🔷 "
Unknown = "❓ "
Uos = "🐲 "
Void = "  "
Windows = "🪟 "
symbol1 = "☁️  "
symbol2 = "󰠅 "
symbol3 = "🐃 "
symbol4 = "🥟 "
symbol5 = " "
symbol6 = "△ "
symbol7 = "⚙️ "
symbol8 = "🅒 "
symbol9 = "⬢"
symbola = "🔮 "
symbolb = "Λ "
symbolc = "🎯 "
symbold = "🦕 "
read_only = "🔒"
symbole = "🐳 "
symbolf = " "
symbolg = " "
symbolh = " "
symboli = "🧅 "
symbolj = " "
symbolk = ""
tag_symbol = " 🏷  "
symboll = "⭐ "
symbolm = " "
symboln = "⌘ "
symbolo = "⎈ "
ssh_symbol = "🌐 "
symbolp = "✦"
symbolq = " "
symbolr = "🅺 "
symbols = "☸ "
symbolt = "🌙 "
symbolu = "🐏 "
symbolv = "🔥 "
symbolw = "✉️ "
symbolx = "🛜"
symboly = "❄️  "
symbolz = ""
symbolaa = "🐫 "
symbolbb = "🪖  "
symbolcc = "📦 "
symboldd = "🧚 "
symbolee = " "
symbolff = "🐍 "
symbolgg = "🦋 "
symbolhh = "🔺 "
symbolii = "📐 "
symboljj = "💎 "
symbolkk = ""
symbolll = "🆂 "
symbolmm = "↕️  "
symbolnn = "🅢 "
symboloo = "❌"
symbolpp = "🧙 "
not_executable_symbol = "🚫"
not_found_symbol = "🔍"
sigint_symbol = "🧱"
signal_symbol = "⚡"
symbolqq = "💠 "
symbolrr = "🐦 "
symbolss = "↯ "

