format = """
[](#3B4252)\
$username\
[](fg:#3B4252 bg:#434C5E)\
$container\
[](fg:#434C5E bg:#4C566A)\
$directory\
[](fg:#4C566A bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$os\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
[](fg:#06969A bg:#33658A)\
$time\
[](fg:#33658A)
$character"""
command_timeout = 5000
scan_timeout = 1000

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[ $user ]($style)'

[container]
symbol = ""
format = '[ $symbol $name ]($style)'
style = 'bg:#434C5E'
disabled = false

[directory]
style = 'bg:#4C566A'
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
# Shorten some long paths by text replacement
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " " 
"dots" = " "
".config" = " "
".local" = "⌘ "

[git_branch]
symbol = ""
style = "fg:#3B4252 bg:#86BBD8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bold red bg:#86BBD8"
format = '[$all_status$ahead_behind ]($style)'

[os]
disabled = false
style = "bg:#06969A"
format = "[ $symbol ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'

[os.symbols]
AIX = "➿"
Alpaquita = "🔔"
AlmaLinux = "💠"
Alpine = "🏔️"
Amazon = "🙂"
Android = "🤖"
Arch = ""
Artix = ""
Bluefin = "🐟"
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = "🐉"
Emscripten = "🔗"
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "🦅"
Gentoo = ""
HardenedBSD = "🛡️"
Illumos = "🐦"
Kali = ""
Linux = ""
Mabox = "📦"
Macos = ""
Manjaro = ""
Mariner = "🌊"
MidnightBSD = "🌘"
Mint = ""
NetBSD = "🚩"
NixOS = ""
Nobara = ""
OpenBSD = ""
OpenCloudOS = "☁️"
openEuler = "🦉"
openSUSE = ""
OracleLinux = "🦴"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "🧪"
Solus = ""
SUSE = ""
Ubuntu = ""
Ultramarine = "🔷"
Unknown = "❓"
Uos = "🐲"
Void = ""
Windows = ""

# Programming Languages

[c]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#06969A"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'
