# ~/.config/environment.d/envvars.conf

MAIN=DP-1
DUMMY=HDMI-A-1
EDITOR=nvim
TZ=America/Chicago
WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
LANG=en_US.UTF-8
LC_CTYPE=${LANG}
LC_COLLATE=${LANG}

XDG_CACHE_HOME=${HOME}/.cache
XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state

HOMEPAGE_VAR_ADGUARD_USER=eric
HOMEPAGE_VAR_ADGUARD_PASSWORD=100204180

FZF_ALT_C_COMMAND="fd --type d"
FZF_DEFAULT_COMMAND="fd --type f"
FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}

NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
NPM_CONFIG_PREFIX=${XDG_CONFIG_HOME}/npm
NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc

GNUPGHOME=${XDG_DATA_HOME}/gnupg
CARGO_HOME=${XDG_DATA_HOME}/cargo
DOTS=${HOME}/src/gh/dcoffline/dots
GEMINI_CLI_HOME=${XDG_CONFIG_HOME}
DOTNET_CLI_HOME=${XDG_DATA_HOME}/dotnet
ATUIN_CONFIG_DIR=${XDG_CONFIG_HOME}/atuin
WAKATIME_HOME=${XDG_CONFIG_HOME}/wakatime
ANDROID_USER_HOME=${XDG_DATA_HOME}/android
GROQDIR=${HOME}/src/gh/dcoffline/groq-dictate
