# ~/.config/environment.d/envvars.conf

MAIN=DP-1
DUMMY=HDMI-A-1
EDITOR=nvim
LANG=en_US.UTF-8
LC_CTYPE=${LANG}
LC_COLLATE=${LANG}
TZ=America/Chicago

DOTS=${HOME}/src/gh/dc/dots
GROQDIR=${HOME}/src/gh/dcoffline/groq-dictate

FZF_ALT_C_COMMAND="fd --type d"
FZF_DEFAULT_COMMAND="fd --type f"
FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}

XDG_CACHE_HOME=${HOME}/.cache
XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state

NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
NPM_CONFIG_PREFIX=${XDG_CONFIG_HOME}/npm
NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc

GEMINI_CLI_HOME=${XDG_DATA_HOME}
GNUPGHOME=${XDG_DATA_HOME}/gnupg
WAKATIME_HOME=${XDG_DATA_HOME}/wakatime
ANDROID_USER_HOME=${XDG_DATA_HOME}/android
ATUIN_CONFIG_DIR=${XDG_CONFIG_HOME}/atuin
