- System:
    - Cloudflare:
        icon: cloudflare
        href: https://dash.cloudflare.com/67304fcb508ed8114c9625fb9a98aff1/one/networks/connectors/cloudflare-tunnels/cloudflared/f675bd2e-853b-481a-8242-3dab60bfa54e/edit/public-hostname
        description: Reverse-Proxy
        server: podman
        container: cloudflared
    - Cockpit:
        icon: cockpit-light
        href: https://cockpit.hemati.com
        description: Bazzite Dashboard
        ping: http://192.168.1.18:9090
- AI:
    - Ollama:
        icon: ollama
        href: https://ai.hemati.com
        description: Local AI Instance
        server: podman
        container: ollama
    - Hermes:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/hermes-agent.png
        href: https://agent.hemati.com
        description: Local AI Harness
        server: podman
        container: hermes
- Security:
    - Pi-hole:
        icon: pi-hole
        href: https://pi.hemati.com/admin
        description: DNS & Ad-blocker
        ping: https://pi.hemati.com/admin
        widget:
          type: pihole
          url: http://host.containers.internal:8080
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
- Sharing:
    - Sunshine:
        icon: sunshine
        href: https://sunshine.hemati.com
        description: Remote Desktop
        ping: http://localhost:47990
    - Vaultwarden:
        icon: bitwarden
        href: https://vault.hemati.com
        description: Password Manager
        server: podman
        container: vaultwarden
- Containers:
    - Nextcloud:
        icon: nextcloud
        href: https://cloud.hemati.com
        description: Private File Storage
        server: podman
        container: nextcloud
    - Immich:
        icon: immich
        href: https://photos.hemati.com
        description: Photo & Video Backup
        server: podman
        container: immich-server
    - PKA Dashboard:
        icon: https://hemati.com/wp-content/uploads/2026/07/imageedit_4_9275255851.png
        href: https://pka.hemati.com
        description: Knowledge-base
        server: podman
        container: pka-web
    - Syncthing:
        icon: syncthing
        href: https://sync.hemati.com
        description: File Management
        server: podman
        container: syncthing
- Stremio:
    - Stremio:
        icon: stremio
        #href: https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F100.120.205.70%3A11470#
        href: https://stremio.hemati.com
        description: Freedom to Stream 
        server: podman
        container: stremio-server
    - AIOStreams:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/aiostreams-light.png
        href: https://aiostreams.hemati.com
        description: Stream Aggregator
        server: podman
        container: aiostreams
    - AIOMetadata:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/aiometadata.png
        href: https://aiometadata.hemati.com
        description: Metadata Provider
        server: podman
        container: aiometadata
    - MediaFlow:
        icon: https://mediaflowtools.com/mediaflow-logo.svg
        href: https://mediaflow.hemati.com
        description: Debrid Cache Proxy
        server: podman
        container: mediaflow
- Jellyfin:
    - Jellyfin:
        icon: jellyfin
        href: https://media.hemati.com
        description: Home Media Server
        server: podman
        container: jellyfin
    - Riven:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/riven.svg
        href: https://riven.hemati.com
        description: Media Discovery Engine
        server: podman
        container: riven
    - Samba:
        icon: samba-server
        href: https://app.plex.tv
        description: Media SMB Share
        server: podman
        container: samba
    - Zurg:
        icon: real-debrid
        href: https://zurg.hemati.com
        description: Organize Media 
        server: podman
        container: zurg
