- System:
    - Cockpit:
        icon: cockpit-light
        href: https://cockpit.hemati.com
        description: Bazzite Dashboard
        ping: http://192.168.1.18:9090
    - Cloudflare:
        icon: cloudflare
        href: https://dash.cloudflare.com/67304fcb508ed8114c9625fb9a98aff1/one/networks/connectors/cloudflare-tunnels/cloudflared/f675bd2e-853b-481a-8242-3dab60bfa54e/edit/public-hostname
        description: Reverse-Proxy
        server: podman
        container: cloudflared
- Servers:
    - Sunshine:
        icon: sunshine
        href: https://sunshine.hemati.com
        description: Remote Desktop
        ping: http://localhost:47990
    - Vaultwarden:
        icon: bitwarden
        href: https://vault.hemati.com
        description: Password Manager
        server: podman
        container: vaultwarden
- Security:
    - Pi-hole:
        icon: pi-hole
        href: https://pi.hemati.com/admin
        description: DNS & Ad-blocker
        ping: https://pi.hemati.com/admin
        widget:
          type: pihole
          url: http://host.containers.internal:8080
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"
          fields: ["queries", "blocked", "blocked_percent", "gravity"]
- Containers:
    - Nextcloud:
        icon: nextcloud
        href: https://cloud.hemati.com
        description: Private File Storage
        server: podman
        container: nextcloud
    - Immich:
        icon: immich
        href: https://photos.hemati.com
        description: Photo & Video Backup
        server: podman
        container: immich-server
    - Ollama:
        icon: ollama
        href: https://ai.hemati.com
        description: Local AI Instance
        server: podman
        container: ollama
    - Hermes:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/hermes-agent.png
        href: https://agent.hemati.com
        description: Local AI Harness
        server: podman
        container: hermes
- Stremio:
    - Stremio:
        icon: stremio
        #href: https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2F100.120.205.70%3A11470#
        href: https://stremio.hemati.com
        description: Freedom to Stream 
        server: podman
        container: stremio-server
    - AIOStreams:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/aiostreams-light.png
        href: https://aiostreams.hemati.com
        description: Stream Aggregator
        server: podman
        container: aiostreams
    - AIOMetadata:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/aiometadata.png
        href: https://aiometadata.hemati.com
        description: Metadata Provider
        server: podman
        container: aiometadata
    - MediaFlow:
        icon: https://mediaflowtools.com/mediaflow-logo.svg
        href: https://mediaflow.hemati.com
        description: Debrid Cache Proxy
        server: podman
        container: mediaflow
- Jellyfin:
    - Jellyfin:
        icon: jellyfin
        href: https://media.hemati.com
        description: Home Media Server
        server: podman
        container: jellyfin
    - Samba:
        icon: samba-server
        href: https://app.plex.tv
        description: Media SMB Share
        server: podman
        container: samba
    - Seerr:
        icon: seerr
        href: https://seerr.hemati.com
        description: Media Discovery Engine
        server: podman
        container: seerr
    - SeerrBridge:
        icon: https://avatars.githubusercontent.com/u/130290673?s=400&v=4
        href: https://seerrbridge.hemati.com
        description: Bridge Seerr to Jellyfin
        server: podman
        container: seerrbridge
    - Zurg:
        icon: real-debrid
        href: https://zurg.hemati.com
        description: Organize Media 
        server: podman
        container: zurg
