title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: false

layout:
  Infrastructure:
    style: row
    columns: 5
  Media:
    style: row
    columns: 5
  Streaming:
    style: row
    columns: 4
  Bookmarks:
    style: row
    columns: 4
