title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: false

layout:
  Containers:
    style: row
    columns: 4
  System:
    style: row
    columns: 3
  Bookmarks:
    style: row
    columns: 6
