title: Hemati Homelab
theme: dark
color: slate
headerStyle: boxed
statusStyle: "dot"
hideVersion: false
useEqualHeights: true

layout:
  System:
    header: false
  Utilities:
    header: false
  Security:
    header: false
  "AI Stack":
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4
  Bookmarks:
    header: true
    style: row
    columns: 4
